{
    "name": "pro_recruitment V17",
    "name": " Pro Recruitment V17",
    "author": "Abdulrhman Mohammed Abdeldaiem",
    "maintainers": ["mashendi"],
    "version": "17.0",
    "depends": [
        "hr_appraisal",
        "hr_recruitment",
        "hr_skills",
        "bounce_v17",
        "survey",
        "hr_recruitment_survey",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/emp_appraisal.xml",
        "views/employee_min_skill.xml",
        "views/hr_appraisal_goal.xml",
        "views/hr_appraisal.xml",
        "views/hr_job.xml",
        "views/hr_applicant.xml",
        "views/hr_skills.xml",
        "views/job_position_criteria.xml",
        "views/survey.xml",
        "views/bounce.xml",
        "views/emp_job_position.xml",
        "views/hr_depart_obj.xml",
        "views/disability.xml",
        "views/company.xml",
        "views/hr_employee.xml",
        "views/performance_level.xml",
        "views/tech_criteria.xml",
        "views/hr_contract.xml",
        "reports/recruitment.xml",
        "reports/emp_appraisal.xml",
        "reports/survey.xml",
        "reports/appraisal.xml",
    ],
    "license": "LGPL-3",
    "installable": True,
    "application": True,
}
